name: gnn_workshop
channels:
- pytorch
- conda-forge
dependencies:
- python==3.10
- pip
- pytorch::pytorch=2.0.1
- pip:
  - torch-cluster==1.6.1
  - torch-scatter==2.1.1
  - torch-geometric==2.3.0
  - lightning==2.0.3
  - aim==3.17.5
  - hydra-core==1.3.2
  - biopython==1.81
  - pandas==2.1.1
  - plotly==5.17.0
  - dash==2.13.0
